apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: autoflow
type: Opaque
stringData:
  NODE_ENV: production
  PORT: "3005"

  MONGO_URI: "mongodb://notification_admin:REPLACE_ME@mongodb-notification.autoflow.svc.cluster.local:27017/notification?authSource=admin"

  RABBITMQ_URL: "amqp://admin:REPLACE_ME@rabbitmq.autoflow.svc.cluster.local:5672"
